"""Project and optional React/Vite starter generation."""

from __future__ import annotations

import re
from pathlib import Path


def create_project(destination: Path, *, react: bool = False) -> None:
    """Create a non-destructive runnable Pyrora project."""
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]*", destination.name):
        raise ValueError("Project name must start with a letter and use letters, numbers, '_' or '-'.")
    if destination.exists():
        raise RuntimeError(f"Destination already exists: {destination}")
    destination.mkdir(parents=True)
    _write(destination / "pyproject.toml", _project_pyproject(destination.name))
    _write(destination / "README.md", _project_readme(destination.name, react))
    _write(destination / "app.py", "from backend.app import app\n")
    _write(destination / "backend" / "__init__.py", "")
    _write(destination / "backend" / "app.py", _backend_app(react))
    _write(destination / "backend" / "templates" / "home.html", _HOME_TEMPLATE)
    _write(destination / "backend" / "static" / ".gitkeep", "")
    if react:
        _create_react(destination / "frontend")


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _project_pyproject(name: str) -> str:
    normalized = name.lower().replace("_", "-")
    return f'''[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "{normalized}"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["pyrora>=0.1.0"]

[tool.setuptools.packages.find]
include = ["backend*"]
'''


def _backend_app(react: bool) -> str:
    cors = ""
    frontend = ""
    if react:
        cors = '''from starlette.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

'''
        frontend = '    frontend_dist=ROOT.parent / "frontend" / "dist",\n    spa_fallback=True,\n'
    return f'''from pathlib import Path

from pyrora import Pyrora, json, render

ROOT = Path(__file__).parent

app = Pyrora(
    root_path=ROOT,
{frontend})
{cors}@app.get("/")
async def home(request):
    return render(request, "home.html", title="Welcome to Pyrora")


@app.get("/api/health")
async def health(request):
    return json({{"ok": True}})
'''


def _project_readme(name: str, react: bool) -> str:
    frontend = "" if not react else '''
## React frontend

In a second terminal, run `pyrora frontend install`, then `pyrora frontend dev`.
For a production frontend, run `pyrora frontend build`; Pyrora serves `frontend/dist`
same-origin with SPA fallback.
'''
    return f'''# {name}

Generated by Pyrora.

```bash
python -m venv .venv
source .venv/bin/activate
pip install -e .
pyrora serve --reload
```
{frontend}'''


def _create_react(frontend: Path) -> None:
    files = {
        "package.json": _PACKAGE_JSON,
        "index.html": _INDEX_HTML,
        "vite.config.ts": _VITE_CONFIG,
        "tsconfig.json": _TSCONFIG,
        "src/main.tsx": _MAIN_TSX,
        "src/App.tsx": _APP_TSX,
        "src/api.ts": _API_TS,
        "src/realtime.ts": _REALTIME_TS,
        "src/webrtc.ts": _WEBRTC_TS,
        "src/styles.css": _STYLES_CSS,
        "src/components/AppShell.tsx": _SHELL_TSX,
        "src/pages/ChatPage.tsx": _CHAT_TSX,
        "src/pages/RoomPage.tsx": _ROOM_TSX,
    }
    for relative, contents in files.items():
        _write(frontend / relative, contents)


_HOME_TEMPLATE = '''<!doctype html>
<html><head><title>{{ title }}</title></head>
<body><main><h1>{{ title }}</h1><p>Your Pyrora app is running.</p></main></body></html>
'''

_PACKAGE_JSON = '''{
  "name": "pyrora-react-frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {"dev": "vite", "build": "tsc --noEmit && vite build", "preview": "vite preview"},
  "dependencies": {"@vitejs/plugin-react": "latest", "vite": "latest", "react": "latest", "react-dom": "latest"},
  "devDependencies": {"@types/react": "latest", "@types/react-dom": "latest", "typescript": "latest"}
}
'''

_INDEX_HTML = '''<!doctype html>
<html lang="en"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Pyrora Realtime</title></head>
<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>
'''

_VITE_CONFIG = '''import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      "/api": "http://127.0.0.1:8000",
      "/ws": { target: "ws://127.0.0.1:8000", ws: true },
      "/signaling": { target: "ws://127.0.0.1:8000", ws: true }
    }
  }
});
'''

_TSCONFIG = '''{
  "compilerOptions": {"target": "ES2020", "useDefineForClassFields": true, "lib": ["ES2020", "DOM", "DOM.Iterable"], "types": ["vite/client"], "allowJs": false, "skipLibCheck": true, "esModuleInterop": true, "allowSyntheticDefaultImports": true, "strict": true, "module": "ESNext", "moduleResolution": "Bundler", "resolveJsonModule": true, "isolatedModules": true, "noEmit": true, "jsx": "react-jsx"},
  "include": ["src", "vite.config.ts"]
}
'''

_MAIN_TSX = '''import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles.css";

ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
'''

_APP_TSX = '''import { useState } from "react";
import { AppShell } from "./components/AppShell";
import { ChatPage } from "./pages/ChatPage";
import { RoomPage } from "./pages/RoomPage";

export default function App() {
  const [page, setPage] = useState<"chat" | "room">("chat");
  return <AppShell page={page} onNavigate={setPage}>{page === "chat" ? <ChatPage /> : <RoomPage />}</AppShell>;
}
'''

_API_TS = '''const API_BASE = import.meta.env.VITE_API_URL ?? "";

export async function health(): Promise<{ ok: boolean }> {
  const response = await fetch(`${API_BASE}/api/health`);
  if (!response.ok) throw new Error(`Health check failed: ${response.status}`);
  return response.json();
}
'''

_REALTIME_TS = '''export class RealtimeClient {
  private socket: WebSocket;
  constructor(path: string, onMessage: (message: unknown) => void) {
    const explicit = import.meta.env.VITE_WS_URL as string | undefined;
    const origin = explicit ?? `${location.protocol === "https:" ? "wss" : "ws"}://${location.host}`;
    this.socket = new WebSocket(`${origin}${path}`);
    this.socket.onmessage = (event) => onMessage(JSON.parse(event.data));
  }
  send(message: unknown) { this.socket.send(JSON.stringify(message)); }
  close() { this.socket.close(); }
}
'''

_WEBRTC_TS = '''import type { RealtimeClient } from "./realtime";

export function createPeerConnection(signaling: RealtimeClient, peerId?: string) {
  const peer = new RTCPeerConnection({ iceServers: [{ urls: "stun:stun.l.google.com:19302" }] });
  peer.onicecandidate = ({ candidate }) => { if (candidate) signaling.send({ event: "ice-candidate", to: peerId, candidate }); };
  return {
    peer,
    async offer() { const offer = await peer.createOffer(); await peer.setLocalDescription(offer); signaling.send({ event: "offer", to: peerId, sdp: offer }); },
    async accept(message: any) {
      if (message.event === "offer") { await peer.setRemoteDescription(message.sdp); const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); signaling.send({ event: "answer", to: message.from, sdp: answer }); }
      if (message.event === "answer") await peer.setRemoteDescription(message.sdp);
      if (message.event === "ice-candidate" && message.candidate) await peer.addIceCandidate(message.candidate);
    },
    hangup() { signaling.send({ event: "hangup", to: peerId }); peer.close(); }
  };
}
'''

_SHELL_TSX = '''import type { ReactNode } from "react";

export function AppShell({ page, onNavigate, children }: {page: "chat" | "room"; onNavigate: (page: "chat" | "room") => void; children: ReactNode}) {
  return <div className="shell"><header><strong>Pyrora</strong><nav><button className={page === "chat" ? "active" : ""} onClick={() => onNavigate("chat")}>Chat</button><button className={page === "room" ? "active" : ""} onClick={() => onNavigate("room")}>WebRTC room</button></nav></header><main>{children}</main></div>;
}
'''

_CHAT_TSX = '''import { useEffect, useState } from "react";
import { health } from "../api";
import { RealtimeClient } from "../realtime";

export function ChatPage() {
  const [status, setStatus] = useState("Checking API…");
  const [messages, setMessages] = useState<string[]>([]);
  const [value, setValue] = useState("");
  const [client, setClient] = useState<RealtimeClient | null>(null);
  useEffect(() => { health().then(() => setStatus("API healthy")).catch((error) => setStatus(error.message)); }, []);
  function connect() { const next = new RealtimeClient("/ws/chat", (message) => setMessages((old) => [...old, JSON.stringify(message)])); setClient(next); }
  function send() { if (value && client) { client.send({ message: value }); setValue(""); } }
  return <section><h1>Realtime chat</h1><p>{status}</p><button onClick={connect} disabled={!!client}>Connect</button><div className="messages">{messages.map((message, index) => <p key={index}>{message}</p>)}</div><div className="composer"><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Message" /><button onClick={send}>Send</button></div></section>;
}
'''

_ROOM_TSX = '''import { useRef, useState } from "react";
import { RealtimeClient } from "../realtime";
import { createPeerConnection } from "../webrtc";

export function RoomPage() {
  const [room, setRoom] = useState("demo");
  const [status, setStatus] = useState("Choose a room, then join from another browser.");
  const localVideo = useRef<HTMLVideoElement>(null);
  async function join() {
    let connection: ReturnType<typeof createPeerConnection> | undefined;
    const client = new RealtimeClient(`/signaling/${encodeURIComponent(room)}`, async (message: any) => {
      setStatus(`Signal: ${message.event}`);
      if (message.event === "peer-joined") await connection?.offer();
      if (["offer", "answer", "ice-candidate"].includes(message.event)) await connection?.accept(message);
    });
    connection = createPeerConnection(client);
    const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
    stream.getTracks().forEach((track) => connection.peer.addTrack(track, stream));
    if (localVideo.current) localVideo.current.srcObject = stream;
    setStatus("Joined signaling room. Browser permission and STUN/TURN policy affect calls.");
  }
  return <section><h1>WebRTC room</h1><p>{status}</p><div className="composer"><input value={room} onChange={(event) => setRoom(event.target.value)} /><button onClick={join}>Join room</button></div><video ref={localVideo} autoPlay muted playsInline /></section>;
}
'''

_STYLES_CSS = '''* { box-sizing: border-box; } body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #f7f7fb; color: #1d1d2b; } .shell { max-width: 920px; margin: auto; min-height: 100vh; padding: 1rem; } header { display: flex; flex-wrap: wrap; gap: 1rem; align-items: center; justify-content: space-between; padding: 1rem 0; } nav { display: flex; gap: .5rem; } button { border: 0; border-radius: .5rem; padding: .65rem 1rem; cursor: pointer; background: #e6e6ef; } button.active, button:hover { background: #5a45d8; color: white; } section { background: white; padding: clamp(1rem, 4vw, 2rem); border-radius: 1rem; box-shadow: 0 8px 30px #2e28541a; } .composer { display: flex; gap: .5rem; margin-top: 1rem; } input { min-width: 0; flex: 1; padding: .65rem; border: 1px solid #c8c8d6; border-radius: .5rem; } .messages { min-height: 8rem; margin-top: 1rem; overflow-wrap: anywhere; } video { width: 100%; max-height: 55vh; margin-top: 1rem; background: #111; border-radius: .75rem; } @media (max-width: 500px) { .shell { padding: .75rem; } .composer { flex-direction: column; } }
'''
